cmake_minimum_required(VERSION 3.13)
project(nvm_tests C)
enable_testing()
add_executable(test_nvm test_nvm.c ../src/xmega_nvm.c)
target_include_directories(test_nvm PRIVATE ../src)
if(MSVC)
    target_compile_options(test_nvm PRIVATE /W4 /UNDEBUG)
else()
    target_compile_options(test_nvm PRIVATE -Wall -Wextra -Werror -UNDEBUG)
endif()
add_test(NAME nvm COMMAND test_nvm)
